sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        G4Thj9bYrHBfJjyCdC/d45DAgqc1UY0m60G368Dek9B/UgjPu7Dcht8It9HgwA0MDm9a2jUSKRka5RocMsc2JxTlzng94nErFvAGn+hoRJLCHRF87isT2zpx9UR1EdavdfQwZD54xgKFnYtrLEUcBNE//3xqrKkYnBMsXlCb6Y7JOwEVRyD64jxz5FsofSDAtVV4opKcxHaIY8997WdOMMHfwcvgOVn3NVKQ7W56AbsBgP35WE5fWk4tOzAeRmtV8zxzc4fwwT76YHoboIJDosqHN6HwpXdvbTbqgG76BOTYAa/0DR5ZY7tEiy92WJ2BN7NyeSofnmXZjSx9knYt/mgUqqLRivdsXl4/FyVkiKVPWPtLfW9bdYMNT6uG26fcq8lMERbgHFIFrgRFpux3u5wgfSTyl7Q9Pe9b8dodmkWPg7papizK9sQ5FKb+MsRaflBGFyLhUqXDuNmKOHMRvuSt27zwJU0Px99nHjD8VBuYDJeg5ErqTpxVElv8CwRAH9umMrW6cMnESEWAc6eENDnznr1dMq+ti/YBQrfBTOdd1Yor0pgoz/Y4b7XGL+NueoBJwAD06IBXM3LCD7yC2MM4xxtqpiju+UTyeAL3m8ogysHrG77cWcTdb4zMcXpkNgrSr/+dKBTZhZkzOavwmyhFSKtlrqLL4Hms7w0u9WY=
    - secure: >-
        guIH6bHZEo1kONHuWxWmVBNgaFb/exoN96V2i4gxFoQ+su4ykunXIyMmQWeTuAbp4+5ZIVwjju+hMSAa+Mc0PKaSlAcWBbYg34n0OPFhn06cnOj8c0hHX5Crfw/OqeOetVrpDpLNU/rE2Nb+TkrQ0XoOfFvqrmCZoxbdHRBwOKlUnXqWzrPcFYOHXlAGma07wHL29s8eT5SPLoEUmFargfDD7aCQsN+hZN3ALlKRUQyOIv72jz5vPFl+rNj5A1AfQdSN7FGU4Ssj9Y2Hk6DW5G42d6DakPks3Lb3FU9c/5WeXASZtUGbvT2ezJesZv5LaSfgp2B4+3ciCi/8rtXmZ4+7Jl+7WOVI74PUorS+29OVh6UY7Vg/UTDA1R7929wnI9K8pCk7F2bpEShm3bSb3jv9UMYFAddNY+5oxRj7spI0BjYpWoUpDIuSkGZ5CGZRjep16Nbf92NZa4neehtFS3b7hnedvYCavOwBBhYYrRQy0m8haNJG/vum38S4htTBbzF9MkAKjloIh+n6KhmxhaF1KPqEC9bV5qJJpUY7anYBrCqhzVhRV1P3Qswd5aL+9so3/mlOPELTtBm3bHKLriHZt/UZeFhUCUwyEZMCbBwMwVTyS4MkjKLQ+prVYEKwINiY6jdDMkSAhuy9hkkefPsKXNkCurc8jSgfiIvvHUk=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
